services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      NEXT_WEBPACK_USEPOLLING: 1
    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
      - ./next-app/package.json:/app/package.json
      - ./next-app/next.config.js:/app/next.config.js
      - ./next-app/tsconfig.json:/app/tsconfig.json
      - ./next-app/postcss.config.js:/app/postcss.config.js
      - ./next-app/tailwind.config.js:/app/tailwind.config.js
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
